### PR TITLE
CU-1u9efkx - Bump agent version to 0.1.57

### PR DESCRIPTION
**Pull request by rannyeli**
Dependent on: https://github.com/komodorio/komodor-agent/pull/76

### CODE REVIEW

**Comment by MickaelAlliel** [comment]
Task linked: [CU-1u9efkx Bump agent version to 0.1.57](https://app.clickup.com/t/1u9efkx)

**Comment by MickaelAlliel** [comment]
@rannyeli https://rnd.komodor.com/onboarding/agent-release this is now done automaticlly in CI. Once you merge the agent and unblock the publish process, it triggers CI for this repo and you don't need this PR :)

**Comment by rannyeli** [comment]
> @rannyeli https://rnd.komodor.com/onboarding/agent-release this is now done automaticlly in CI. Once you merge the agent and unblock the publish process, it triggers CI for this repo and you don't need this PR :)

Amazing! closing.

**Pull request closed without merging**
